"use client";

import React, { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import {
  AuditResults,
  PerformanceSnapshot,
  PpcAnalysisCard,
  TopOpportunities,
  ListingHealthSection,
  RevenueGapSection,
  AdEfficiencySection,
  type AnalysisResult,
  type ListingHealthSnapshot,
  type RevenueGapReport,
  type AdEfficiencySignal,
} from "@/components/AuditResults";

// ── Types ───────────────────────────────────────────────────────────────────

interface BrandAnalysis {
  summary:               string;
  competitive_landscape: string;
  top_seller_traits:     string[];
}

interface SharedAudit {
  audit_id:        string;
  brand_name:      string;
  niche:           string;
  marketplace:     string;
  report_type:     string;
  audit_purpose:   string;
  created_at:      string;
  brand_analysis:  BrandAnalysis;
  benchmark_metrics: { key: string; label: string; unit: string; industry_avg: number; lower_is_better: boolean }[];
  citations:       string[];
  csv_metadata?:   { columns?: string[]; preview?: Record<string, string>[]; raw_text?: string };
  raw_text?:       string;
  deep_analysis?:  AnalysisResult & {
    listingHealthSnapshot?: ListingHealthSnapshot;
    revenueGapReport?: RevenueGapReport;
    adEfficiencySignal?: AdEfficiencySignal;
    compiledReport?: { executiveSummary?: string; totalMonthlyOpportunity?: number; topActions?: { action: string; estimatedImpact: string }[] };
  };
}

const STRATEGY_CALL_URL = "https://launch.withrevlyn.com/widget/bookings/discovery-call-with-revlyn";

// ── Page ────────────────────────────────────────────────────────────────────

export default function SharePage() {
  const { token } = useParams<{ token: string }>();
  const [audit, setAudit]     = useState<SharedAudit | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState<string | null>(null);

  useEffect(() => {
    fetch(`/api/share/${token}`)
      .then((r) => r.ok ? r.json() : r.json().then((d: { detail?: string }) => Promise.reject(d.detail ?? "Not found")))
      .then(setAudit)
      .catch((e: unknown) => setError(String(e)))
      .finally(() => setLoading(false));
  }, [token]);

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center">
        <div className="text-center space-y-3">
          <div className="w-8 h-8 rounded-full border-2 border-amber-400 border-t-transparent animate-spin mx-auto" />
          <p className="text-sm text-slate-400">Loading report...</p>
        </div>
      </div>
    );
  }

  if (error || !audit) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center px-4">
        <div className="text-center max-w-sm space-y-3">
          <div className="w-12 h-12 rounded-full bg-red-500/10 border border-red-500/30 flex items-center justify-center mx-auto">
            <svg className="h-6 w-6 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
            </svg>
          </div>
          <p className="text-slate-200 font-medium">Report not found</p>
          <p className="text-sm text-slate-500">{error ?? "This link may have expired or been removed."}</p>
        </div>
      </div>
    );
  }

  const da = audit.deep_analysis;
  const isNewFormat = !!da?.listingHealthSnapshot;
  const date = new Date(audit.created_at).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  // Extract data for new-format audits
  const scorecard = da?.listingHealthSnapshot ?? null;
  const revenueGap = da?.revenueGapReport ?? null;
  const adEfficiency = da?.adEfficiencySignal ?? null;
  // ── New format layout ──
  if (isNewFormat && scorecard) {
    return (
      <div className="min-h-screen bg-slate-950 text-slate-100">
        <style>{`
          @media print {
            @page {
              size: A4;
              margin: 14mm 16mm 16mm 16mm;
              @bottom-center {
                content: "Generated by Revlyn";
                font-size: 9pt;
                color: #94a3b8;
              }
              @top-center { content: none; }
              @bottom-left { content: none; }
              @bottom-right { content: none; }
              @top-left { content: none; }
              @top-right { content: none; }
            }
            .no-print, header { display: none !important; }
            .print-only { display: block !important; }
            main { padding: 0 !important; max-width: 100% !important; }
            * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }

            /* Base: clean white background, near-black text */
            html, body, .min-h-screen, .bg-slate-950, .bg-slate-900\\/50 {
              background: #ffffff !important;
              color: #0f172a !important;
            }

            /* Text colours */
            .text-slate-100, .text-slate-200, .text-slate-300 { color: #1e293b !important; }
            .text-slate-400 { color: #475569 !important; }
            .text-slate-500, .text-slate-400 { color: #64748b !important; }
            .text-white { color: #0f172a !important; }

            /* Cards: white bg, light border */
            .rounded-2xl, .rounded-xl {
              background: #f8fafc !important;
              border-color: #e2e8f0 !important;
              box-shadow: none !important;
            }

            /* Accent badges */
            .bg-slate-800 { background: #f1f5f9 !important; }
            .bg-slate-900 { background: #f8fafc !important; }
            .border-slate-700, .border-slate-800 { border-color: #cbd5e1 !important; }
            .text-slate-300 { color: #334155 !important; }

            /* Coloured status badges */
            .bg-emerald-500\\/10 { background: #d1fae5 !important; }
            .bg-amber-500\\/10  { background: #fef3c7 !important; }
            .bg-red-500\\/10    { background: #fee2e2 !important; }
            .bg-blue-500\\/10   { background: #dbeafe !important; }
            .border-emerald-500\\/20 { border-color: #6ee7b7 !important; }
            .border-amber-500\\/20  { border-color: #fcd34d !important; }

            /* Headings */
            h1, h2, h3 { color: #0f172a !important; }
            .text-amber-400, .text-amber-500 { color: #b45309 !important; }
            .text-emerald-400, .text-emerald-500 { color: #047857 !important; }
            .text-blue-400 { color: #1d4ed8 !important; }
            .text-red-400  { color: #b91c1c !important; }

            /* Locked section cards — hide in PDF */
            .locked-section { display: none !important; }

            /* Page breaks */
            .rounded-2xl, .rounded-xl { page-break-inside: avoid; }
            a.flex { page-break-inside: avoid; }
            h3 { page-break-after: avoid; }
            .print-break-before { page-break-before: always; }
          }
        `}</style>

        {/* Print-only header */}
        <div className="print-only hidden mb-8">
          <div className="flex items-center justify-between pb-5" style={{borderBottom: "2px solid #e2e8f0"}}>
            <div>
              <p className="text-[10px] font-bold uppercase tracking-widest text-amber-600 mb-1">Amazon Account Scorecard</p>
              <h1 className="text-2xl font-bold text-slate-900">{audit.brand_name}</h1>
              {audit.niche && (
                <p className="text-sm text-slate-500 mt-0.5">{audit.niche} · {audit.marketplace || "Amazon US"}</p>
              )}
            </div>
            <div className="text-right flex flex-col items-end gap-1">
              <p className="text-xs text-slate-400">Prepared by</p>
              <div style={{background: "#1e293b", borderRadius: "8px", padding: "8px 14px", display: "inline-flex", alignItems: "center", gap: "8px"}}>
                <img src="/logo.png" alt="Revlyn" style={{height: "32px", width: "auto"}} />
                <span style={{fontSize: "14px", fontWeight: "700", color: "#f97316", letterSpacing: "0.05em"}}>Amazon Auditer</span>
              </div>
              <p className="text-[10px] text-slate-400">{date}</p>
            </div>
          </div>
        </div>

        {/* Header */}
        <header className="border-b border-slate-800 bg-slate-900/50 backdrop-blur no-print">
          <div className="mx-auto flex h-14 max-w-5xl items-center justify-between px-4">
            <div className="flex items-center gap-3">
              <img src="/logo.png" alt="Revlyn" className="h-10 w-auto" />
              <span className="text-lg font-bold tracking-wide bg-gradient-to-r from-orange-400 via-amber-400 to-orange-300 bg-clip-text text-transparent">Amazon Auditer</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-slate-500">Report prepared {date}</span>
              <button
                onClick={() => {
                  const orig = document.title;
                  document.title = `${audit.brand_name} — Amazon Account Scorecard`;
                  window.print();
                  document.title = orig;
                }}
                className="flex items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-800 px-3 py-1.5 text-xs font-medium text-slate-300 hover:border-slate-600 hover:text-white transition-colors"
              >
                <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                    d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Export PDF
              </button>
            </div>
          </div>
        </header>

        <main className="mx-auto max-w-5xl px-4 py-10 space-y-10">
          {/* Brand header card */}
          <div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6">
            <h1 className="text-2xl font-bold text-slate-100">{audit.brand_name}</h1>
            <div className="flex flex-wrap gap-2 mt-2">
              {audit.niche && (
                <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-slate-800 text-slate-300 border border-slate-700">{audit.niche}</span>
              )}
              <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-slate-800 text-slate-300 border border-slate-700">
                {audit.marketplace || "Amazon US"}
              </span>
            </div>
            {audit.brand_analysis?.summary && (
              <p className="mt-3 text-sm text-slate-400 max-w-xl leading-relaxed">{audit.brand_analysis.summary}</p>
            )}
          </div>

          {/* Page 1: Account Scorecard (always visible) */}
          <section>
            <h3 className="text-lg font-semibold text-slate-100 mb-4 flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-blue-500/20 border border-blue-500/40 flex items-center justify-center text-xs text-blue-400 font-bold">1</span>
              Account Scorecard
            </h3>
            <ListingHealthSection data={scorecard} />
          </section>

          {/* Page 2: Revenue Gap Analysis — only shown if data exists */}
          {revenueGap && (
            <section>
              <h3 className="text-lg font-semibold text-slate-100 mb-4 flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-amber-500/20 border border-amber-500/40 flex items-center justify-center text-xs text-amber-400 font-bold">2</span>
                Revenue Gap Analysis
              </h3>
              <RevenueGapSection data={revenueGap} />
            </section>
          )}

          {/* Page 3: Advertising Efficiency — only shown if data exists */}
          {adEfficiency && (
            <section>
              <h3 className="text-lg font-semibold text-slate-100 mb-4 flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-red-500/20 border border-red-500/40 flex items-center justify-center text-xs text-red-400 font-bold">3</span>
                Advertising Efficiency
              </h3>
              <AdEfficiencySection data={adEfficiency} />
            </section>
          )}
        </main>

        <footer className="border-t border-slate-800 mt-16 py-6 no-print">
          <p className="text-center text-xs text-slate-400">Prepared with Amazon Audit &middot; {date}</p>
        </footer>
      </div>
    );
  }

  // ── Legacy layout (old audits with performanceSnapshot/ppcAnalysis) ──
  let sectionNum = 0;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      <style>{`
        @media print {
          @page {
            size: A4;
            margin: 14mm 16mm 16mm 16mm;
            @bottom-center {
              content: "Generated by Revlyn";
              font-size: 9pt;
              color: #94a3b8;
            }
            @top-center { content: none; }
            @bottom-left { content: none; }
            @bottom-right { content: none; }
            @top-left { content: none; }
            @top-right { content: none; }
          }
          .no-print, header { display: none !important; }
          .print-only { display: block !important; }
          main { padding: 0 !important; max-width: 100% !important; }
          * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }

          /* Base: clean white background, near-black text */
          html, body, .min-h-screen, .bg-slate-950, .bg-slate-900\\/50 {
            background: #ffffff !important;
            color: #0f172a !important;
          }

          /* Text colours */
          .text-slate-100, .text-slate-200, .text-slate-300 { color: #1e293b !important; }
          .text-slate-400 { color: #475569 !important; }
          .text-slate-500, .text-slate-400 { color: #64748b !important; }
          .text-white { color: #0f172a !important; }

          /* Cards: white bg, light border */
          .rounded-2xl, .rounded-xl {
            background: #f8fafc !important;
            border-color: #e2e8f0 !important;
            box-shadow: none !important;
          }

          /* Accent badges */
          .bg-slate-800 { background: #f1f5f9 !important; }
          .bg-slate-900 { background: #f8fafc !important; }
          .border-slate-700, .border-slate-800 { border-color: #cbd5e1 !important; }
          .text-slate-300 { color: #334155 !important; }

          /* Coloured status badges */
          .bg-emerald-500\\/10 { background: #d1fae5 !important; }
          .bg-amber-500\\/10  { background: #fef3c7 !important; }
          .bg-red-500\\/10    { background: #fee2e2 !important; }
          .bg-blue-500\\/10   { background: #dbeafe !important; }
          .border-emerald-500\\/20 { border-color: #6ee7b7 !important; }
          .border-amber-500\\/20  { border-color: #fcd34d !important; }

          /* Headings */
          h1, h2, h3 { color: #0f172a !important; }
          .text-amber-400, .text-amber-500 { color: #b45309 !important; }
          .text-emerald-400, .text-emerald-500 { color: #047857 !important; }
          .text-blue-400 { color: #1d4ed8 !important; }
          .text-red-400  { color: #b91c1c !important; }

          /* Page breaks */
          .rounded-2xl, .rounded-xl { page-break-inside: avoid; }
          a.flex { page-break-inside: avoid; }
          h3 { page-break-after: avoid; }
        }
      `}</style>

      {/* Print-only header */}
      <div className="print-only hidden mb-8">
        <div className="flex items-center justify-between pb-5" style={{borderBottom: "2px solid #e2e8f0"}}>
          <div>
            <p className="text-[10px] font-bold uppercase tracking-widest text-amber-600 mb-1">Amazon Account Scorecard</p>
            <h1 className="text-2xl font-bold text-slate-900">{audit.brand_name}</h1>
            {audit.niche && (
              <p className="text-sm text-slate-500 mt-0.5">{audit.niche} · {audit.marketplace || "Amazon US"}</p>
            )}
          </div>
          <div className="text-right">
            <p className="text-xs text-slate-400 mb-0.5">Prepared by</p>
            <p className="text-base font-bold text-slate-800">Revlyn</p>
            <p className="text-[10px] text-slate-400 mt-0.5">{date}</p>
          </div>
        </div>
      </div>

      {/* Header */}
      <header className="border-b border-slate-800 bg-slate-900/50 backdrop-blur no-print">
        <div className="mx-auto flex h-14 max-w-5xl items-center justify-between px-4">
          <span className="text-base font-semibold text-amber-400 tracking-tight">Amazon Audit</span>
          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-500">Report prepared {date}</span>
            <button
              onClick={() => {
                const orig = document.title;
                document.title = `${audit.brand_name} — Amazon Account Scorecard`;
                window.print();
                document.title = orig;
              }}
              className="flex items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-800 px-3 py-1.5 text-xs font-medium text-slate-300 hover:border-slate-600 hover:text-white transition-colors"
            >
              <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Export PDF
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-4 py-10 space-y-8">
        {/* Metadata card */}
        <div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6">
          <h1 className="text-2xl font-bold text-slate-100">{audit.brand_name}</h1>
          <div className="flex flex-wrap gap-2 mt-2">
            {audit.niche && (
              <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-slate-800 text-slate-300 border border-slate-700">{audit.niche}</span>
            )}
            <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-slate-800 text-slate-300 border border-slate-700">{audit.marketplace}</span>
          </div>
          {audit.audit_purpose && (
            <p className="mt-3 text-sm text-slate-400 max-w-xl">{audit.audit_purpose}</p>
          )}
        </div>

        {/* Brand Analysis */}
        {audit.brand_analysis?.summary && (
          <section>
            <h2 className="text-lg font-semibold text-slate-100 mb-4 flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-blue-500/20 border border-blue-500/40 flex items-center justify-center text-xs text-blue-400 font-bold">{++sectionNum}</span>
              Brand &amp; Niche Analysis
            </h2>
            <div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 space-y-5">
              <div>
                <p className="text-xs uppercase tracking-widest font-semibold text-slate-500 mb-2">Brand Summary</p>
                <p className="text-sm text-slate-300 leading-relaxed">{audit.brand_analysis.summary}</p>
              </div>
              {audit.brand_analysis.competitive_landscape && (
                <div>
                  <p className="text-xs uppercase tracking-widest font-semibold text-slate-500 mb-2">Competitive Landscape</p>
                  <p className="text-sm text-slate-300 leading-relaxed">{audit.brand_analysis.competitive_landscape}</p>
                </div>
              )}
              {audit.brand_analysis.top_seller_traits?.length > 0 && (
                <div>
                  <p className="text-xs uppercase tracking-widest font-semibold text-slate-500 mb-3">What Top Sellers Do</p>
                  <div className="flex flex-wrap gap-2">
                    {audit.brand_analysis.top_seller_traits.map((t, i) => (
                      <span key={i} className="px-3 py-1.5 rounded-lg bg-blue-500/10 border border-blue-500/30 text-xs text-blue-300">{t}</span>
                    ))}
                  </div>
                </div>
              )}
              {audit.citations?.length > 0 && (
                <div className="flex flex-wrap gap-2 pt-2 border-t border-slate-800">
                  {audit.citations.map((url, i) => (
                    <a key={i} href={url} target="_blank" rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 text-xs text-slate-500 hover:text-slate-300 transition-colors">
                      <svg className="h-3 w-3 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                          d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                      </svg>
                      Source {i + 1}
                    </a>
                  ))}
                </div>
              )}
            </div>
          </section>
        )}

        {/* AI Analysis — 4-layer or legacy */}
        {da && typeof da === "object" && da.listingHealthSnapshot ? (
          <section>
            <h2 className="text-lg font-semibold text-slate-100 mb-6 flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-purple-500/20 border border-purple-500/40 flex items-center justify-center text-xs text-purple-400 font-bold">{++sectionNum}</span>
              Audit Report
            </h2>
            <AuditResults data={da as AnalysisResult} />
          </section>
        ) : (
          <>
            {da && typeof da === "object" && da.performanceSnapshot && (
              <section>
                <h2 className="text-lg font-semibold text-slate-100 mb-6 flex items-center gap-2">
                  <span className="w-6 h-6 rounded-full bg-purple-500/20 border border-purple-500/40 flex items-center justify-center text-xs text-purple-400 font-bold">{++sectionNum}</span>
                  AI Performance Snapshot
                </h2>
                <PerformanceSnapshot
                  data={da.performanceSnapshot}
                  source={(da as AnalysisResult).performanceSnapshot_source}
                />
              </section>
            )}
            {da && typeof da === "object" && da.ppcAnalysis && (
              <section>
                <h2 className="text-lg font-semibold text-slate-100 mb-4 flex items-center gap-2">
                  <span className="w-6 h-6 rounded-full bg-amber-500/20 border border-amber-500/40 flex items-center justify-center text-xs text-amber-400 font-bold">{++sectionNum}</span>
                  PPC Performance
                </h2>
                <PpcAnalysisCard data={da.ppcAnalysis} />
              </section>
            )}
          </>
        )}

        {/* Top 3 Opportunities (legacy only) */}
        {da && typeof da === "object" && da.topOpportunities && !da.listingHealthSnapshot && (
          <section>
            <h2 className="text-lg font-semibold text-slate-100 mb-6 flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-amber-500/20 border border-amber-500/40 flex items-center justify-center text-xs text-amber-400 font-bold">{++sectionNum}</span>
              Top 3 Opportunities
            </h2>
            <TopOpportunities
              data={da.topOpportunities}
              source={(da as AnalysisResult).topOpportunities_source}
            />
          </section>
        )}

        {/* CTA */}
        <section>
          <div className="rounded-2xl border border-emerald-500/30 bg-gradient-to-br from-emerald-500/10 to-slate-900/50 p-8 text-center space-y-4">
            <h3 className="text-2xl font-bold text-slate-100">Ready to Unlock These Opportunities?</h3>
            <p className="text-sm text-slate-400 max-w-lg mx-auto">
              Our team will walk you through these findings and build a custom action plan to grow your Amazon business.
            </p>
            <a
              href={STRATEGY_CALL_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-emerald-500 hover:bg-emerald-400 text-white font-semibold px-8 py-4 rounded-xl text-lg transition-colors shadow-lg shadow-emerald-500/20"
            >
              Book a Strategy Call
            </a>
            <p className="text-xs text-slate-500">No commitment required &mdash; 30 minutes, completely free</p>
          </div>
        </section>
      </main>

      <footer className="border-t border-slate-800 mt-16 py-6 no-print">
        <p className="text-center text-xs text-slate-400">Prepared with Amazon Audit &middot; {date}</p>
      </footer>
    </div>
  );
}
